### ISSUE TITLE
我正在参考你的项目做一些事，有几个疑问想咨询一下你。

### ISSUE THREAD

**Issue by hawskpy** [donwg/examples-make#1]
你好！
我正在参考你的项目实现Android平台上通过RTMP推送H.264 H.265到服务器上，重点是H.265.

我发现在UtilRtmp.h 中 Send265Videoframe方法 是将I帧 中的 psp pps vps 逐帧传过来， 再调用SendVideoSpsPpsVps 封装后发出，P帧则继续往下运行最后SendPacket 发送出去。 目前我们的视频流是psp pps vps 后面还有视频数据 你是怎么处理的喃？

如有空可以加微信（微信号：hawkspy）个好友交流一下。

**Comment by dontls** [comment]
处理流程是一样的。
1、I帧解析sps、pps、vps信息后，先发送sps/pps/vps(编码信息没有改变发送一次也可以)，在发送I帧
2、p帧直接发送（其余帧一样）
